- name: "Reinstall HTTPD configuration with SSL support"
  include_role: 
    name: urpg-httpd
  vars: 
    use_secure_mode: 1
    certificate_file_path: "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.crt"
    key_file_path: "{{ letsencrypt_keys_dir }}/{{ domain_name }}.key"