- name: "Get the latest release metadata of {{ artifact_id }}"
  uri:
    url: "https://api.github.com/repos/{{github_user}}/{{github_repo}}/releases/latest"
    return_content: yes
    headers:
      Authorization: "token {{ artifact_download_token }}"
  register: github_response

- set_fact:
    binary_asset_url: "{{  github_response.json.assets|json_query(query) }}"
  vars:
    query: "[?starts_with(name,'{{ artifact_id }}')].url | [0]"   

- name: "Get the latest release URI of {{ artifact_id }}"
  uri:
    url: "{{ binary_asset_url }}"
    return_content: no
    follow_redirects: none
    status_code: 302
    headers:
      Authorization: "token {{ artifact_download_token }}"
      Accept: "application/octet-stream"
  register: assets

- name: Create urpg-server folder
  file: 
    path: "{{ ansible_env.HOME }}/urpg-server"
    state: directory

- name: "Download the latest release of {{ artifact_id }}"
  get_url:
    url: "{{ assets.location }}"
    dest: "{{ jar_destination }}"
    mode: 0755

- name: Install URPG Server service file
  become: yes
  template:
    src: 'urpgserver.service.j2'
    dest: '/etc/systemd/system/multi-user.target.wants/urpgserver.service'
    mode: '644'
    owner: root
    group: root
  register: service_file

- name: Invoke systemctl daemon reload if URPG Server service file was changed
  become: yes
  systemd:
    daemon_reload: yes
  when: service_file.changed

- name: Ensure URPG Server is running; don't restart if it's already running and the service file wasn't changed
  become: yes
  service:
    name: urpgserver 
    state: started
  when: service_file.changed == false

- name: Restart URPG Server because the config file changed
  become: yes
  service:
    name: urpgserver
    state: restarted
  when: service_file.changed