- name: Install HTTPD with Yum 
  become: yes
  yum:
    name: httpd
    state: present

- name: Configure HTTPD to start on server boot
  become: yes
  service:
    name: httpd
    enabled: yes

- name: Install HTTPD configuration file
  become: yes
  template:
    src: 'httpd.conf.j2'
    dest: '/etc/httpd/conf/httpd.conf'
    mode: '0644'
    backup: yes
    owner: root
    group: root
  register: config_file

- name: Ensure HTTPD is running; don't restart if it's already running and the config file wasn't changed
  become: yes
  service:
    name: httpd 
    state: started
  when: config_file.changed == false

- name: Restart HTTPD because the config file changed
  become: yes
  service:
    name: httpd
    state: restarted
  when: config_file.changed