- name: "Get the latest release metadata of {{ artifact_id }} version {{ version_to_release }}"
  uri:
    url: "https://api.github.com/repos/{{github_user}}/{{github_repo}}/releases/tags/{{ version_to_release }}"
    return_content: yes
    headers:
      Authorization: "token {{ artifact_download_token }}"
  register: github_response

- set_fact:
    binary_asset_url: "{{  github_response.json.assets|json_query(query) }}"
  vars:
    query: "[?starts_with(name,'{{ artifact_id }}')].url | [0]"  

- name: "Get the release URI of {{ artifact_id }} version {{ version_to_release }}"
  uri:
    url: "{{ binary_asset_url }}"
    return_content: no
    follow_redirects: none
    status_code: 302
    headers:
      Authorization: "token {{ artifact_download_token }}"
      Accept: "application/octet-stream"
  register: assets

- name: "Create download folder for {{ artifact_id }} at {{ download_path }}"
  become: yes
  file: 
    path: "{{ download_path }}"
    state: directory

- name: "Download {{ artifact_id }} version {{ version_to_release }}" 
  become: yes
  get_url:
    url: "{{ assets.location }}"
    dest: "{{ download_path }}/{{ artifact_id }}.active.{{ archive_extension }}"
    mode: 0755
  register: artifact_archive

- name: Remove {{ artifact_id }} folder on the webserver
  become: yes
  file: 
    path: "{{ unarchive_path }}"
    state: absent
  when: artifact_archive.changed

- name: Check whether the {{ artifact_id }} folder on the webserver exists
  stat: 
    path: "{{ unarchive_path }}"
  register: unarchive_path_data

- debug: 
    msg: "{{ unarchive_path_data }}"

- name: Create {{ artifact_id }} folder on the webserver
  become: yes
  file: 
    path: "{{ unarchive_path }}"
    state: directory
  when: artifact_archive.changed or not unarchive_path_data.stat.exists
  register: unarchive_folder_status

- name: Unarchive the contents of the artifact into the {{ artifact_id }} folder on the webserver
  become: yes
  unarchive:
    remote_src: yes
    src: "{{ download_path }}/{{ artifact_id }}.active.{{ archive_extension }}"
    dest: "{{ unarchive_path }}"
  when: artifact_archive.changed or unarchive_folder_status.changed

- name: Find all main.*.copy-for-wp.js files in the {{ urpg_webapps_artifact_id }} folder on the webserver
  become: yes
  find:
    paths: "{{ urpg_webapps_path }}"
    patterns: 'main.*.copy-for-wp.js'
  register: main_files

- name: Update main.*.copy-for-wp.js files with correct base href
  become: yes
  lineinfile:
    path: "{{ item[0].path }}"
    regexp: "{{ item[1].regexp }}"
    line: "{{ item[1].line }}"
  with_nested:
    - "{{ main_files.files }}"
    - [
        {
          'regexp': "useValue: '/urpg-webapps/'", 
          'line': "useValue: '/'"
        }
      ]

- name: Update main.*.copy-for-wp.js files to to use correct sessionService.login URL
  become: yes
  replace:
    path: "{{ item.path }}"
    regexp: "^.*this.sessionService.login\\(.urpg-webapps. \\+ this.route\\['_routerState'\\].snapshot.url\\);"
    replace: "this.sessionService.login(this.route['_routerState'].snapshot.url);"
  with_items: "{{ main_files.files }}"

- name: Update main.*.copy-for-wp.js files to use window.location.href
  become: yes
  replace:
    path: "{{ item.path }}"
    regexp: "^.*this.router.navigateByUrl\\('/', {\n^.*skipLocationChange: true\n^.*}\\).then\\(\\(\\) => this.router.navigate\\(\\[url\\]\\)\\);"
    replace: "window.location.href = '/urpg-webapps' + url;"
  with_items: "{{ main_files.files }}"

- name: Update theme header.php file with base href
  become: yes
  replace:
    path: "{{ unarchive_path }}/header.php"
    regexp: "<!--base href goes here-->"
    replace: "<base href=\"/urpg-webapps/\">"

- name: Update theme header.php file with viewport meta
  become: yes
  replace:
    path: "{{ unarchive_path }}/header.php"
    regexp: "<!--viewport meta goes here-->"
    replace: "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"

- name: Update theme header.php file with angular stylesheet
  become: yes
  replace:
    path: "{{ unarchive_path }}/header.php"
    regexp: "<!--angular stylesheet goes here-->"
    replace: "<link rel=\"stylesheet\" href=\"styles.142f45b89e80ca43.css\">"

- name: Update theme header.php file with app-root
  become: yes
  replace:
    path: "{{ unarchive_path }}/header.php"
    regexp: "<!--app-root goes here-->"
    replace: "<urpg-root loadcomponent=\"urpg-site-header\"></urpg-root>"

- name: Update theme header.php file with angular scripts
  become: yes
  replace:
    path: "{{ unarchive_path }}/header.php"
    regexp: "<!--angular scripts go here-->"
    replace: "<script src=\"runtime.1e14c86517b5c878.js\" type=\"module\"></script><script src=\"polyfills.1e57298bf69966e4.js\" type=\"module\"></script><script src=\"scripts.76dd17c1368a8a57.js\" defer></script><script src=\"main.ea962ed9770d955d.copy-for-wp.js\" type=\"module\"></script>"