- name: Find all main.*.copy-for-wp.js files in the {{ urpg_webapps_artifact_id }} folder on the webserver
  become: yes
  find:
    paths: "{{ urpg_webapps_path }}"
    patterns: 'main.*.copy-for-wp.js'
  register: main_files

- name: Update main.*.copy-for-wp.js file with correct base href
  become: yes
  lineinfile:
    path: "{{ main_files.files[0].path }}"
    regexp: "useValue: '/urpg-webapps/'"
    line: "useValue: '/'"
  when: main_files.files is defined and main_files.files|length > 0

- name: Update main.*.copy-for-wp.js file to to use correct sessionService.login URL
  become: yes
  replace:
    path: "{{ main_files.files[0].path }}"
    regexp: "^.*this.sessionService.login\\(.urpg-webapps. \\+ this.route\\['_routerState'\\].snapshot.url\\);"
    replace: "this.sessionService.login(this.route['_routerState'].snapshot.url);"
  when: main_files.files is defined and main_files.files|length > 0

- name: Update main.*.copy-for-wp.js file to use window.location.href
  become: yes
  replace:
    path: "{{ main_files.files[0].path }}"
    regexp: "^.*this.router.navigateByUrl\\('/', {\n^.*skipLocationChange: true\n^.*}\\).then\\(\\(\\) => this.router.navigate\\(\\[url\\]\\)\\);"
    replace: "window.location.href = '/urpg-webapps' + url;"
  when: main_files.files is defined and main_files.files|length > 0