- name: Install EPEL Repo with Yum
  become: yes
  yum: 
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install Remi Repo with Yum 
  become: yes
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install PHP Extensions with Yum
  become: yes
  yum: name={{ item }}
  loop: "{{ php_modules }}"
  register: php_module_installs_for_middleware

- name: Configure PHP-FPM to start on server boot
  become: yes
  service:
    name: php82-php-fpm
    enabled: yes

- name: Ensure PHP-FPM is running
  become: yes
  service:
    name: php82-php-fpm
    state: started

- set_fact: 
    num_installed_php_modules_for_middleware: "{{ php_module_installs_for_middleware.results | selectattr('changed', 'true') | list | length }}"

- name: Restart HTTPD because we installed PHP modules for middleware
  become: yes
  service:
    name: httpd
    state: restarted
  when: num_installed_php_modules_for_middleware|int > 0