- hosts: localhost
  roles:
    - role: urpg-db
      tags: [ db ]
    - role: urpg-server
      tags: [ java, server, urpgserver, urpg-server ]
    - role: urpg-httpd
      tags: [ httpd ]
    - role: urpg-letsencrypt
      tags: [ letsencrypt, ssl, cert, certificate ]
    - role: urpg-middleware
      tags: [ middleware, php ]
    - role: urpg-webapps
      tags: [ angular, web, webapps, urpgwebapps, urpg-webapps ]
    - role: urpg-wordpress
      tags: [ wordpress, wp ]